### ISSUE TITLE
I18n project

### ISSUE THREAD

**Issue by AugustinMauroy** [statichunt/geeky-nextjs#13]
How to i18n this project ?
I'm interest to use this "template" but I want to use i18n. So have you idea ?

**Comment by tfsomrat** [comment]
Hello @AugustinMauroy 

thanks for choosing our theme, please follow this official doc for i18n https://docs.astro.build/en/recipes/i18n/

and if you need professional help, then we are available to hire.

**Comment by AugustinMauroy** [comment]
Ok thanks I will do this.
